# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20151009_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exam'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='place',
            field=models.CharField(default='', max_length=254, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_allowed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time Allowed'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='kind',
            field=models.CharField(default='', max_length=254, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.TextField(blank=True, default='', verbose_name='Title'),
        ),
    ]
