# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20150930_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course'},
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.IntegerField(blank=True, default=1, verbose_name='Term'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='kind',
            field=models.CharField(blank=True, max_length=254, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=10, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='place',
            field=models.CharField(blank=True, max_length=254, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Start date'),
        ),
    ]
